[theme]
base = "dark"
primaryColor = "#7C5CFF"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#1c1836"
textColor = "#F5F3FF"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
